--- 

- name: "Allow SSH through firewall"
  ufw:
      rule: allow
      name: OpenSSH

- name: "Enable Firewall"
  ufw:
    state: enabled
    policy: deny
  notify:
      - restart ufw

- name: "Update umask values"
  block:
    - replace:
        path: /etc/login.defs
        regexp: '^UMASK'
        replace: 'UMASK           077'
    - replace:
        path: /etc/login.defs
        regexp: '^USERGROUPS_ENAB'
        replace: 'USERGROUPS_ENAB no'

- name: "Create SSH Certification Authority for SSH Certs"
  block:
    - name: "Create CA directory"
      file:
        path: /var/ca/ssh
        state: directory
    - name: "Create CA"
      shell: 
        cmd: ssh-keygen -C "Security Audit CA" -f security-audit.ca -P ''
        creates: /var/ca/ssh/security-audit.ca
      args:
        chdir: "/var/ca/ssh"
    - name: "Copy admin ssh key"
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /tmp/id_rsa.pub
    - name: "Sign SSH Key"
      shell: "ssh-keygen -s /var/ca/ssh/security-audit.ca -I root  -n root -V +16w -z 2 /tmp/id_rsa.pub"
    - name: "Copy SSH Certificate Back"
      fetch: 
        src: /tmp/id_rsa-cert.pub
        flat: yes
        dest: ./

- name: "Restrict SSH Connections to SSH Certificates only"
  copy: 
      src: files/sshd_config
      dest: /etc/ssh/sshd_config
      validate: '/usr/sbin/sshd -T -f %s'
      backup: yes
      mode: 0644
  notify:
      - restart sshd

- name: "Create audit user"
  user:
    name: "{{ audit_user }}"
    comment: "Audit User"
    shell: /bin/false
    state: present

- name: "Create team member login user"
  user:
    name: "auditor"
    comment: "Auditor Account"
    shell: /bin/bash
    state: present

- name: "Make Ansible Directory"
  file:
    path: /root/ansible-laptop
    state: directory

- name: "Copy Laptop Ansible Files"
  copy: 
    src: ../../../laptop/
    dest: /root/ansible-laptop/

- name: "Install ansible"
  block:
    - name: "Install software-properties-common"
      apt:
        name: software-properties-common
        state: present
    - name: "Add repository"
      apt_repository:
        repo: ppa:ansible/ansible
        update_cache: yes
    - name: "Install package"
      apt:
        name: ansible
        state: present

- name: "Generate SSH Key"
  openssh_keypair:
    path: /root/.ssh/id_rsa

- name: "Sign SSH Key for laptop access"
  shell: "ssh-keygen -s /var/ca/ssh/security-audit.ca -I root  -n root -V +16w -z 2 /root/.ssh/id_rsa.pub"